# These are supported funding model platforms

github: [jpaulet] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: aulet # Replace with a single Patreon username
custom: ['https://gitcoin.co/grants/321/darray'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
